- name: Configure dns server in internal company network
  hosts: dns
  become: yes
  tasks:
    - name: Remove original DNS server
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        line: "nameserver 10.0.2.3"
        state: absent

    - name: Add DNS server
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        line: "nameserver 192.168.62.254"
        state: present

    - name: Install bind
      ansible.builtin.package:
        name: bind
        state: present

    - name: Copy bind config
      ansible.builtin.copy:
        src: ./files/dns/etc/named.conf
        dest: /etc/bind/named.conf

    - name: Copy bind zone file config
      ansible.builtin.copy:
        src: ./files/dns/etc/cybersec.internal
        dest: /var/bind/cybersec.internal

    - name: Enable and start bind
      ansible.builtin.service:
        name: named
        enabled: yes
        state: restarted

- name: Configure dns server in internal company network
  hosts: web, database, employee, debug, companyrouter
  become: yes
  tasks:
    - name: Remove original DNS server
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        line: "nameserver 10.0.2.3"
        state: absent

    - name: Remove isp DNS server
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        line: "nameserver 192.168.62.254"
        state: absent

    - name: Add DNS server
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        line: "nameserver 172.30.0.4"
        state: present
