- name: My first play
  hosts: fake_internet
  tasks:
      - name: Ping my hosts
        ansible.builtin.ping:

      - name: Print message
        ansible.builtin.debug:
            msg: Hello world
