---
- hosts: dc
  vars:
    domain_name: "insecure.cyb"
    local_admin: '.\vagrant'
    dc_password: 'Saturday14th?123'
    recovery_password: 'Saturday14th?123'
  gather_facts: no
  tasks:
  - name: Test connectivity from ansible to windows dc
    ansible.windows.win_ping:

  - name: Disable firewall for Domain, Public and Private profiles
    win_firewall:
      state: disabled
      profiles:
      - Domain
      - Private
      - Public

  - name: Install AD
    win_feature:
      name: AD-Domain-Services
      include_management_tools: yes
      include_sub_features: yes
      state: present
    register: res_ad_install

  - name: Pause for 1 minute to give ad domain services time and create a domain afterwards
    ansible.builtin.pause:
      minutes: 1

  - name: Create Domain
    win_domain:
      dns_domain_name : "{{ domain_name }}"
      safe_mode_password : "{{ recovery_password }}"
    register: res_ad_domain

  - name: Create wip directory to copy files to
    ansible.windows.win_file:
      path: C:\wip
      state: directory

  - name: Create Financial directory for insecure share
    ansible.windows.win_file:
      path: C:\Financial
      state: directory

  - name: Copy txt file to Financial folder
    ansible.windows.win_copy:
      src: rawfiles/sensitive-data.txt
      dest: C:\Financial\sensitive-data.txt

  - name: Copy PowerShell scripts to perform AD stuff, share, dns
    ansible.windows.win_copy:
      src: rawfiles/dc/
      dest: C:\wip

  - name: Add static route for employees network
    community.windows.win_route:
      destination: 172.30.128.0/25
      gateway: 172.30.42.62
      metric: 1
      state: present
  
  - name: Add static route for external (red) network
    community.windows.win_route:
      destination: 192.168.56.0/24
      gateway: 172.30.42.62
      metric: 1
      state: present

  - name: Reboot
    ansible.windows.win_reboot:
    when: (res_ad_install.reboot_required) or (res_ad_domain.reboot_required)

## Before running this playbook do vagrant ssh and run
## (Invoke-WebRequest -UseBasicParsing https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1).content | iex
## add routes
## ROUTE: route /p add 172.30.128.0 mask 255.255.255.192 172.30.42.254 if <nr>
## New-NetRoute -DestinationPrefix "172.30.128.0/25" -InterfaceIndex <nr> -NextHop 172.30.42.254
# Remove-NetRoute -InterfaceAlias "Local Area Connection 42" -DestinationPrefix 0.0.0.0/0
# Set-NetIPAddress -InterfaceIndex <7> -IPAddress 172.30.42.4 -PrefixLength 26
# remove-netroute -interfaceindex <5> -destinationprefix 0.0.0.0/0 (but make sure nat network is connected otherwise can't remove)
