---
- hosts: database
  gather_facts: no
  become: yes
  tasks:
  - name: Copy insecure mysqld conf
    ansible.builtin.copy:
      src: rawfiles/network.cnf
      dest: /etc/my.cnf.d/network.cnf
      owner: root
      group: root
      mode: '0644'
  
  - name: Execute query to allow root/bdup login remotely
    community.mysql.mysql_query:
      query:
      - CREATE USER 'root'@'%' IDENTIFIED BY 'password';
      - CREATE USER 'bdup'@'%' IDENTIFIED BY 'bdup';
      - GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
      - GRANT ALL PRIVILEGES ON *.* TO 'bdup'@'%' WITH GRANT OPTION;
      - FLUSH PRIVILEGES;

  - name: Restart and enable mysql
    ansible.builtin.systemd:
      state: restarted
      enabled: yes
      name: mysqld
    