---
- hosts: router
  become: yes
  vars:
    dhcp_subnets:
      - ip: 172.30.128.0
        netmask: 255.255.255.128
        range_begin: 172.30.128.10
        range_end: 172.30.128.126
  tasks:
    - ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
  roles:
    - bertvv.dhcp

- hosts: web
  become: yes
  tasks:
    - ansible.builtin.command: ip route add 172.30.128.0/25 via 172.30.42.1
  roles:
    - bertvv.httpd
    

- hosts: database
  become: yes
  tasks:
    - ansible.builtin.command: ip route add 172.30.128.0/25 via 172.30.42.1
  roles:
    - bertvv.mariadb
  vars:
    mariadb_bind_address: 0.0.0.0

- hosts: employee1
  become: yes
  tasks:
    - ansible.builtin.command: ip route add 172.30.42.0/26 via 172.30.128.1