---
- hosts: win10
  vars:
    win10_hostname: "employee2"
    domain_name: "insecure.cyb"
    domain_admin: 'vagrant@insecure.cyb'
    domain_admin_pass: 'vagrant'
  gather_facts: no
  tasks:
  - name: Test connectivity from ansible to windows10
    ansible.windows.win_ping:

  - name: Disable firewall for Domain, Public and Private profiles
    win_firewall:
      state: disabled
      profiles:
      - Domain
      - Private
      - Public

  - name: Create wip directory to copy files to
    ansible.windows.win_file:
      path: C:\wip
      state: directory
  
  - name: Copy Sched task script and phone home script
    ansible.windows.win_copy:
      src: rawfiles/winclient
      dest: C:\wip\

  - name: Download wireshark installer to wip
    ansible.windows.win_get_url:
      url: https://1.eu.dl.wireshark.org/win64/Wireshark-win64-3.6.8.exe
      dest: C:\wip\

  - name: Download nmap installer to wip
    ansible.windows.win_get_url:
      url: https://nmap.org/dist/nmap-7.93-setup.exe
      dest: C:\wip\

  - name: Add static route for server network
    community.windows.win_route:
      destination: 172.30.42.0/26
      gateway: 172.30.128.126
      metric: 1
      state: present

  - name: Add static route for external (red) network
    community.windows.win_route:
      destination: 192.168.56.0/24
      gateway: 172.30.128.126
      metric: 1
      state: present

#  - name: Add win10 to domain
#    ansible.windows.win_domain_membership:
#      dns_domain_name: "{{ domain_name }}"
#      hostname: "{{ win10_hostname }}"
#      domain_admin_user: "{{ domain_admin }}"
#      domain_admin_password: "{{ domain_admin_pass }}"
#      state: domain
#    register: domain_state
#
#
#  - name: Reboot
#    ansible.windows.win_reboot:
#    when: domain_state.reboot_required

## Chicken/Egg problem --> cannot be contacted, first need to fix ip
## New-NetRoute -DestinationPrefix "172.30.42.0/26" -InterfaceIndex <nr> -NextHop 172.30.128.1
# TODO rsat tools and not via choco :(